version: '3.7'

services:
  server:
    build: .
    env_file: .env
    image: test/prod-server
    environment:
      - PGHOST=db
      - PGUSER=${POSTGRESS_USER}
      - PGDATABASE=${POSTGRES_DB}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=5432
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
